# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BauerFitPrototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Magpie', :git => 'https://github.com/Hipo/magpie.git', :branch => 'swift-5'

end
